[package]
name = "fastfuzzy"
version = "0.1.0"
authors = ["amiya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
pyo3 = "0.12.3"
strsim = "0.10.0"
regex = "1.4.2"
aho-corasick = "0.7"
ngrams = "1.0.1"
crossbeam = "0.8.0"
crossbeam-channel = "0.5.0"
num_cpus = "1.13.0"

[lib]
name = "fastfuzzy"
crate-type = ["cdylib"]

[[bin]]
name = "bin"
path = "src/bin.rs"